// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const PetDisplay: typeof import('/mnt/c/Users/Rushi/Documents/waitwise/components/PetDisplay')['PetDisplay']
  const QuizWidget: typeof import('/mnt/c/Users/Rushi/Documents/waitwise/components/QuizWidget')['QuizWidget']
  const ReviewHub: typeof import('/mnt/c/Users/Rushi/Documents/waitwise/components/ReviewHub')['ReviewHub']
  const browser: typeof import('wxt/browser/chrome')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { PetAnimationType } from '/mnt/c/Users/Rushi/Documents/waitwise/components/PetDisplay'
  import('/mnt/c/Users/Rushi/Documents/waitwise/components/PetDisplay')
}
